version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: ecolight_mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  
      MYSQL_DATABASE: ecolight_db
      MYSQL_PASSWORD: ecolight_pass
    
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./ecolight-backend/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  backend:
    build: ./ecolight-backend
    container_name: ecolight_backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
    
      
      DB_NAME: ecolight_db

  frontend:
    build: ./ecolight-frontend
    container_name: ecolight_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql_data:
# Copier le script dans l'image

